server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: intel-service
          uri: lb://intel-service
          predicates:
            - Path=/intel/**
          filters :
            - RewritePath=/intel/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: sampleSlowCircuitBreaker
                fallbackUri: forward:/fallback/test
    loadbalancer:
      ribbon:
        enabled: false
logging:
  level:
    org.springframework: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always